matrix:
  include:
    - language: java
      jdk: oraclejdk8

      install: true

      script:
        - ./mvnw clean install
        - ./mvnw test

      cache:
        directories:
        - $HOME/.m2

    - language: node_js
      node_js: 9.11

      before_script:
        - cd client && npm install

      script:
        - npm test

      cache:
        directories:
        - $HOME/.m2
        - "node_modules"